"""initial schema

Revision ID: 43950b6fd0fc
Revises: 
Create Date: 2026-03-17 09:52:28.815284+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43950b6fd0fc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('context_type', sa.String(length=50), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('ai_response', sa.Text(), nullable=False),
    sa.Column('context_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('user_override_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('body_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('bodyweight_lbs', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('body_fat_pct', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_competition', sa.Boolean(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('equipment', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('meets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('federation', sa.String(length=50), nullable=False),
    sa.Column('weight_class_kg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('squat_opener_lbs', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('bench_opener_lbs', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('deadlift_opener_lbs', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('actual_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_unit', sa.String(length=3), nullable=False),
    sa.Column('training_days_per_week', sa.SmallInteger(), nullable=False),
    sa.Column('preferred_rep_schemes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preferred_exercises', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meet_weight_class_kg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('bodyweight_lbs', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('sleep_quality', sa.SmallInteger(), nullable=True),
    sa.Column('fatigue_level', sa.SmallInteger(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('meet_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('program_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meet_id'], ['meets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.SmallInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_exercise_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.SmallInteger(), nullable=False),
    sa.Column('weight_lbs', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('reps', sa.SmallInteger(), nullable=False),
    sa.Column('rpe', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('set_type', sa.String(length=20), nullable=False),
    sa.Column('is_pr', sa.Boolean(), nullable=False),
    sa.Column('e1rm_lbs', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['workout_exercise_id'], ['workout_exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('rep_count', sa.SmallInteger(), nullable=False),
    sa.Column('weight_lbs', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('e1rm_lbs', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('previous_weight_lbs', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personal_records')
    op.drop_table('sets')
    op.drop_table('workout_exercises')
    op.drop_table('programs')
    op.drop_table('workouts')
    op.drop_table('user_preferences')
    op.drop_table('meets')
    op.drop_table('exercises')
    op.drop_table('body_metrics')
    op.drop_table('ai_conversations')
    # ### end Alembic commands ###
